name: Recent Activity

on:
  schedule:
    - cron: '0 */12 * * *' # Update every 12 hour (Runs at 00:00 and 12:00 UTC every day)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@{version}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
