on:
  workflow_dispatch:
  issue_comment:
    types: [created, edited, deleted]

name: Review

jobs:
  update_guestbook:
    name: Update reviews
    if: ${{ github.event.issue.title == 'Review' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Update reviews from comments
        uses: actions/github-script@v6
        with:
          script: |
            const query = `query($owner:String!, $name:String!, $issue_number:Int!) {
              repository(owner:$owner, name:$name){
                issue(number:$issue_number) {
                  comments(first:10,orderBy:{direction:DESC, field:UPDATED_AT}) {
                    nodes {
                      author {
                        avatarUrl(size: 25)
                        login
                        url
                      }
                      bodyText
                      updatedAt
                    }
                  }
                }
              }
            }`;
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
              issue_number: context.issue.number
            }
            const result = await github.graphql(query, variables)
            const renderComments = (comments) => {
              return comments.reduce((prev, curr) => {
                const sanitizedText = curr.bodyText.replace(/(\r\n|\r|\n)/g, "<br />").replace('|', '&#124;');
                return `${prev}|[![${curr.author.login}](${curr.author.avatarUrl})<br />${curr.author.login}](${curr.author.url})|${new Date(curr.updatedAt).toLocaleString()}|${sanitizedText}|\n`;
              }, "| Name | Date | Message |\n|---|---|---|\n");
            };
            const fileSystem = require('fs');
            const readme = fileSystem.readFileSync('README.md', 'utf8');
            fileSystem.writeFileSync('README.md', readme.replace(/(?<=<!-- reviews -->.*\n)[\S\s]*?(?=<!-- \/reviews -->|$(?![\n]))/gm, renderComments(result.repository.issue.comments.nodes)), 'utf8');
      - name: Push reviews update
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email '78082316+Qiamast@users.noreply.github.com'
          git commit -am 'Update: Add new reviews📬'
          git push